#Questions and tasks as a result of the exploration below (in no particular order):


* Exclude amatuer built from main dataset or just filter? = yes, (confirm the nans aren't just N/A because the manufacturer is clearly professional)
* clean up location column 
* consolidate and compare aircraft categories
* triple check missing values
* quadruple check that we aren't missing any US records
* make some charts to see:
  * aircraft category freq
  * city/state freq
  * weather condition freq (if time)
  * phase of flight (other variables such as repair or aircraft age? )
* look at data re: flight volume to contextualize
* look at what type of flights (purpose, aircraft) are more prevalent in an area
* find correlations 






NAN VALUES OF CONCERN
*amateur built
*injury severity


In [ ]:
# uploading file for flatiron lesson
# source: https://towardsdatascience.com/3-ways-to-load-csv-files-into-colab-7c14fcbdcb92
from google.colab import files
uploaded = files.upload()

Saving df_usa_from_state_concat.csv to df_usa_from_state_concat.csv


In [ ]:
import pandas as pd
import csv
import numpy as np

In [ ]:
df = pd.read_csv('df_usa_from_state_concat.csv')

In [ ]:
full_nan_count = df.isna().sum().sum()
full_nan_count 

102412

In [ ]:
#missing injury values might not matter as long as no one was injured
#some of these could be N/A
#look at the city and state ones 
#cut the ones where we don't know if it was amateur built (check record to confirm it's not boeing or something lol)
#other missing values will only matter for certain analysis, it's okay if the base table has some missing values
nan_count = df.isna().sum()
nan_count

Unnamed: 0                    0
Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                      0
Country                       0
Latitude                   3609
Longitude                  3619
Airport.Code               8709
Airport.Name               8176
Injury.Severity              69
Aircraft.damage             547
Aircraft.Category             0
Registration.Number           7
Make                          7
Model                        21
Amateur.Built                 5
Number.of.Engines           798
Engine.Type                2494
FAR.Description               2
Schedule                  23937
Purpose.of.flight          1351
Air.carrier               15290
Total.Fatal.Injuries       3213
Total.Serious.Injuries     3141
Total.Minor.Injuries       2789
Total.Uninjured             783
Weather.Condition           485
Broad.phase.of.flight     19322
Report.Status              2329
Publicat

In [ ]:
df.columns

Index(['Unnamed: 0', 'Event.Id', 'Investigation.Type', 'Accident.Number',
       'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude',
       'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date', 'State', 'City'],
      dtype='object')

In [ ]:
df['Aircraft.damage'].values   

array(['Destroyed', 'Substantial', 'Substantial', ..., 'Substantial',
       'Substantial', 'Substantial'], dtype=object)

In [ ]:
df['Aircraft.damage'].unique()

array(['Destroyed', 'Substantial', 'Minor', nan, 'Unknown'], dtype=object)

In [ ]:
#investigate the unknowns and nans here
df['Aircraft.damage'].value_counts()

Substantial    22155
Destroyed       2862
Minor            575
Unknown           43
Name: Aircraft.damage, dtype: int64

In [ ]:
df['Amateur.Built'].values

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
#investigate the nans here, filter the yes
df['Amateur.Built'].unique()

array(['No', 'Yes', nan], dtype=object)

In [ ]:
df['Amateur.Built'].value_counts()

No     22989
Yes     3188
Name: Amateur.Built, dtype: int64

In [ ]:
#investigate the nans here
df['Injury.Severity'].unique()

array(['Fatal(3)', 'Non-Fatal', 'Fatal(2)', 'Fatal(1)', 'Fatal(4)',
       'Incident', 'Fatal(8)', 'Fatal(5)', 'Fatal', nan, 'Minor',
       'Serious', 'Fatal(6)', 'Fatal(14)', 'Fatal(16)', 'Fatal(9)',
       'Fatal(17)', 'Fatal(228)', 'Fatal(12)', 'Fatal(7)', 'Fatal(10)',
       'Fatal(13)', 'Fatal(27)', 'Fatal(65)', 'Fatal(11)'], dtype=object)

In [ ]:
#all these ranked fatalities pose an issue
df['Injury.Severity'].value_counts()

Non-Fatal     21507
Fatal          3257
Fatal(1)        393
Fatal(2)        242
Minor           181
Incident        164
Serious         138
Fatal(3)         93
Fatal(4)         73
Fatal(5)         20
Fatal(6)         14
Fatal(7)         10
Fatal(8)          5
Fatal(10)         4
Fatal(12)         3
Fatal(65)         1
Fatal(27)         1
Fatal(13)         1
Fatal(14)         1
Fatal(228)        1
Fatal(17)         1
Fatal(9)          1
Fatal(16)         1
Fatal(11)         1
Name: Injury.Severity, dtype: int64

In [ ]:
#consolidate these
df['Aircraft.Category'].unique()

array(['Airplane', 'Helicopter', 'Glider', 'Weight-Shift',
       'Powered Parachute', 'Balloon', 'Gyrocraft', 'Powered-Lift',
       'Ultralight', 'WSFT', 'Blimp', 'Rocket', 'ULTR'], dtype=object)

In [ ]:
df['Aircraft.Category'].value_counts()

Airplane             22550
Helicopter            2499
Glider                 492
Balloon                224
Gyrocraft              152
Weight-Shift           135
Powered Parachute       89
Ultralight              24
WSFT                     9
Powered-Lift             3
Blimp                    3
Rocket                   1
ULTR                     1
Name: Aircraft.Category, dtype: int64

In [ ]:
#investigate the nans here
df['Purpose.of.flight'].unique()

array(['Personal', 'Unknown', 'Instructional', 'Ferry', 'Public Aircraft',
       'Business', nan, 'Positioning', 'Other Work Use',
       'Executive/corporate', 'External Load', 'Public Aircraft - State',
       'Public Aircraft - Federal', 'Aerial Observation',
       'Public Aircraft - Local', 'Skydiving', 'Flight Test',
       'Firefighting', 'PUBS', 'Aerial Application', 'Air Race/show',
       'Banner Tow', 'Air Race show', 'Glider Tow', 'Air Drop', 'ASHO',
       'PUBL'], dtype=object)

In [ ]:
#investigate the nans + unknowns here
df['Purpose.of.flight'].value_counts()

Personal                     16322
Instructional                 3373
Aerial Application            1248
Business                       830
Unknown                        670
Positioning                    496
Other Work Use                 334
Aerial Observation             272
Flight Test                    248
Ferry                          166
Skydiving                      151
Executive/corporate            149
External Load                   96
Air Race show                   79
Public Aircraft - Federal       74
Banner Tow                      65
Public Aircraft - Local         55
Public Aircraft - State         54
Public Aircraft                 53
Glider Tow                      46
Firefighting                    24
Air Race/show                    8
Air Drop                         7
ASHO                             6
PUBS                             4
PUBL                             1
Name: Purpose.of.flight, dtype: int64

In [ ]:
#investigate the nans here
df['Total.Fatal.Injuries'].unique()

array([  3.,   0.,   2.,   1.,  nan,   4.,   8.,   5.,   6.,  10.,   9.,
         7.,  14.,  16.,  17., 228.,  12.,  11.,  13.,  27.,  65.,  49.])

In [ ]:
df['Total.Fatal.Injuries'].value_counts()

0.0      18861
1.0       2279
2.0       1138
3.0        330
4.0        205
5.0         67
6.0         33
7.0         18
10.0         8
8.0          8
9.0          7
12.0         3
14.0         2
16.0         2
11.0         2
17.0         1
228.0        1
13.0         1
27.0         1
65.0         1
49.0         1
Name: Total.Fatal.Injuries, dtype: int64

In [ ]:
df['Total.Fatal.Injuries'].median

<bound method NDFrame._add_numeric_operations.<locals>.median of 0        3.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
26177    0.0
26178    0.0
26179    0.0
26180    1.0
26181    0.0
Name: Total.Fatal.Injuries, Length: 26182, dtype: float64>

In [ ]:
df['Total.Fatal.Injuries'].mean

<bound method NDFrame._add_numeric_operations.<locals>.mean of 0        3.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
26177    0.0
26178    0.0
26179    0.0
26180    1.0
26181    0.0
Name: Total.Fatal.Injuries, Length: 26182, dtype: float64>

In [ ]:
df['Total.Uninjured'].unique()

array([  0.,   4.,   1.,   2.,  36.,   3.,   6.,  10.,   5.,   7.,  nan,
         8.,   9.,  17., 236., 140.,  12.,  13.,  15.,  37., 251.,  23.,
        53., 162.,  70., 120.,  49.,  14.,  59.,  79., 143.,  18.,  60.,
       119.,  68., 113., 203., 588., 157.,  98., 146.,  28., 208., 112.,
        61., 311.,  52., 129.,  47., 142.,  83.,  31., 268., 109., 124.,
        27.,  84., 133.,  77., 122., 165., 190., 151.,  97.,  51., 117.,
        21., 186., 174., 147.,  80.,  65., 121.,  30., 197.,  95.,  11.,
       141., 290., 272., 220.,  20., 102., 136.,  57.,  96., 324., 138.,
        99., 150., 192., 185., 148., 178.,  22., 239., 108., 128.,  73.,
       132.,  67., 306., 250., 257., 194., 111., 130., 298., 175.,  81.,
       182., 279.,  39., 278., 144., 333., 199., 169., 288., 406., 126.,
       338.,  82.,  29., 172.,  16., 149., 100., 216., 501., 125., 263.,
        50.,  32.,  45., 184., 139.,  63.,  85.,  24.,  56.,  41.,  64.,
       189., 114., 214.,  74., 393., 291.,  43., 24

In [ ]:
df['Total.Uninjured'].value_counts()

0.0      8627
1.0      8503
2.0      5319
3.0      1191
4.0       688
         ... 
125.0       1
100.0       1
16.0        1
338.0       1
198.0       1
Name: Total.Uninjured, Length: 231, dtype: int64

In [ ]:
#investigate the nans here
df['Total.Minor.Injuries'].unique()

array([ 0.,  3.,  1.,  2.,  4., nan,  6.,  5.,  9., 25., 14., 42., 50.,
       17.,  7., 24., 33., 12.,  8., 13., 19.])

In [ ]:
df['Total.Minor.Injuries'].value_counts()

0.0     19509
1.0      2878
2.0       763
3.0       144
4.0        61
5.0        11
6.0         7
7.0         5
9.0         3
8.0         2
24.0        1
13.0        1
12.0        1
33.0        1
42.0        1
17.0        1
50.0        1
14.0        1
25.0        1
19.0        1
Name: Total.Minor.Injuries, dtype: int64

In [ ]:
#investigate the nans here
df['Total.Serious.Injuries'].unique()

array([  0.,   2.,   1.,  nan,   8.,   3.,   6.,   4.,  88.,   5.,  25.,
         7., 137.,  41.,  12.,  26.,  20.,  11.,  22.,   9.,  19.,  10.,
       125.,  27.,  13.])

In [ ]:
df['Total.Serious.Injuries'].value_counts()

0.0      18755
1.0       2954
2.0        994
3.0        196
4.0         76
5.0         19
6.0         13
7.0          9
8.0          4
9.0          4
10.0         3
125.0        2
11.0         1
27.0         1
19.0         1
22.0         1
41.0         1
20.0         1
26.0         1
12.0         1
137.0        1
25.0         1
88.0         1
13.0         1
Name: Total.Serious.Injuries, dtype: int64